name: dl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.77
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmpy2=2.1.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - lcms2=2.12
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pytorch=2.5.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pywin32=305
  - pyyaml=6.0.2
  - pyzmq=24.0.1
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wcwidth=0.2.13
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - audioread==3.0.1
    - cffi==1.17.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.54.1
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - librosa==0.10.2.post1
    - llvmlite==0.43.0
    - matplotlib==3.9.2
    - msgpack==1.1.0
    - numba==0.60.0
    - opencv-python==4.10.0.84
    - pandas==2.2.3
    - pooch==1.8.2
    - pycparser==2.22
    - pyparsing==3.2.0
    - pytz==2024.2
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - soundfile==0.12.1
    - soxr==0.5.0.post1
    - threadpoolctl==3.5.0
    - torchaudio==2.5.0
    - torchvision==0.20.0
    - tqdm==4.66.5
    - typing-extensions==4.11.0
    - tzdata==2024.2
